import { Navigation } from '@/components/ui/navigation'
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <meta name='format-detection' content='telephone=no, date=no, email=no, address=no' />
      </head>

      <body className={inter.className}>
        <React.Suspense fallback={<div>Loading...</div>}>
          <Navigation />
        </React.Suspense>
        {children}
      </body>
    </html>
  )
}
